<?php

namespace kodi\common\models\device;

use kodi\common\behaviors\TimestampBehavior;
use kodi\common\enums\Status;
use kodi\common\enums\DeviceType;
use kodi\common\models\user\User;
use Yii;
use yii\db\ActiveRecord;
use yii\validators\ExistValidator;
use yii\validators\NumberValidator;
use yii\validators\RangeValidator;
use yii\validators\RequiredValidator;
use yii\validators\StringValidator;

/**
 * Class `Device`
 * ==============
 *
 * This is the model class for table "{{%device}}".
 * It represents information about device.
 * It may be mobile application as well as native machine app
 *
 * Available table columns:
 * ------------------------
 *
 * @property integer $id
 * @property integer $uuid Unique id of device generated by itself
 * @property integer $user_id Id of the user who owns the device
 * @property string $type Type of the device (Mobile or Kiosk)
 * @property string $name
 * @property string $photo
 * @property string $status
 * @property string $location_latitude
 * @property string $location_longitude
 * @property integer $created_at
 * @property integer $updated_at
 *
 * Available AR relations:
 * -----------------------
 *
 * @property User $user
 *
 */
class Device extends ActiveRecord
{
    /**
     * @inheritdoc
     */
    public static function tableName(): string
    {
        return '{{%device}}';
    }

    /**
     * @inheritdoc
     */
    public function rules(): array
    {
        return [

            // Required fields
            [['user_id', 'uuid'], RequiredValidator::class],

            // Strings validation
            [['photo'], StringValidator::class, 'max' => 255],
            [['name', 'location_latitude', 'location_longitude'], StringValidator::class, 'max' => 64],

            // Range validation
            ['status', RangeValidator::class, 'range' => array_keys(Status::listData())],
            ['type', RangeValidator::class, 'range' => array_keys(DeviceType::listData())],

            // Numbers validation
            [['user_id'], NumberValidator::class, 'integerOnly' => true],

            // Existence validation
            [['user_id'], ExistValidator::class, 'targetClass' => User::class, 'targetAttribute' => 'id'],
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels(): array
    {
        return [
            'id' => Yii::t('common', 'ID'),
            'uuid' => Yii::t('common', 'Unique ID'),
            'user_id' => Yii::t('common', 'Owner ID'),
            'name' => Yii::t('common', 'Name'),
            'photo' => Yii::t('common', 'Photo'),
            'location_latitude' => Yii::t('common', 'Latitude'),
            'location_longitude' => Yii::t('common', 'Longitude'),
        ];
    }

    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            TimestampBehavior::className(),
        ];
    }

    /**
     * @inheritdoc
     */
    public function beforeSave($insert): bool
    {
        // Set auto-generated fields
        if (empty($this->photo)) {
            $this->photo = null;
        }

        return parent::beforeSave($insert);
    }

    /**
     * Returns related user.
     */
    public function getUser()
    {
        return $this->hasOne(User::class, ['id' => 'user_id']);
    }

    /**
     * @return string
     */
    public function getPhoto()
    {
        if (!empty($this->photo)) {
            return $this->photo;
        }

        return '/img/no-photo-android.png';
    }

}
